---
title: "Sources"
format: html
---

Barrera, Adriana. “Who Is Xochitl Galvez, the Maverick Opposition Candidate Seeking Mexico’s Presidency?” Reuters, May 31, 2024. https://www.reuters.com/world/americas/xochitl-galvez-maverick-opposition-candidate-seeking-mexicos-presidency-2024-05-31/.

Encyclopædia Britannica. “Mexico - Federalism, Constitution, Autonomy.” Encyclopædia Britannica, May 9, 2025. https://www.britannica.com/place/Mexico/Government-and-society.

FBI. “Violent Crime.” FBI, 2019. https://ucr.fbi.gov/crime-in-the-u.s/2019/crime-in-the-u.s.-2019/topic-pages/violent-crime.
Freedom House. “Mexico: Freedom in the World 2024 Country Report.” Freedom House. Accessed May 12, 2025. https://freedomhouse.org/country/mexico/freedom-world/2024.

Hackbarth, Kurt. “Assessing AMLO: The Presidential Years.” Jacobin. Accessed May 12, 2025.
https://jacobin.com/2025/04/amlo-mexico-workers-social-programs.

Instituo Nacional Electoral. “Cómputos Distritales 2024: Elecciones Federales: Presidencial,” 2024. https://computos2024.ine.mx/presidencia/base-de-datos.

———. “Votos en Coalición.” Instituo Nacional Electoral, n.d. https://ayuda.ine.mx/2021/informate/assets/docs/Votaciones/Votos_en_Coalicion.pdf.
Instituto Nacional de Estadística y Geografía. “Censo de Población y Vivienda 2020,” 2020. https://www.inegi.org.mx/programas/ccpv/2020/#Microdatos.

———. “Encuesta Nacional de Ingresos y Gastos de Los Hogares,” 2022. https://www.inegi.org.mx/programas/enigh/nc/2022/.
Instituto Nacional de los Pueblos Indígenos. “Población Indígena Autoadscrita Nacional y Por Entidad Federativa-Muestra Censal 2020,” 2020. https://www.inpi.gob.mx/indicadores2020/1-poblacion-indigena-autoadscrita-nacional-y-por-entidad-federativa-muestra-censal-2020.xlsx.

Osgood, Brian. “What to Know about Mexico’s 2024 Presidential Election.” Al Jazeera, May 27, 2024. https://www.aljazeera.com/news/2024/5/27/what-to-know-about-the-mexicos-2024-presidential-election.

Reuters. “Mexico’s Sheinbaum Says Indigenous Rights a Priority for Constitutional Reforms.” Reuters, June 18, 2024. https://www.reuters.com/world/americas/mexicos-sheinbaum-says-indigenous-rights-priority-constitutional-reforms-2024-06-18/.

Secretariado Ejecutivo del Sistema Nacional de Seguridad Pública. “Cifras de Incidencia Delictiva Estatal, 2015 - Marzo 2025,” 2025. https://drive.google.com/file/d/1Sql1YZEziX_Ndu22g4BpnWcVlsNYHr1t/view?usp=sharing.

Woodman, Connor. “Left Populism Has Become Mexico’s New Normal. At What Cost?” Novara Media (blog), May 11, 2024. https://novaramedia.com/2024/11/05/left-populism-has-become-mexicos-new-normal-at-what-cost/.
